import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import * as lumos from "@ckb-lumos/lumos";

const inter = Inter({ subsets: ["latin"] });
Object.assign(globalThis, { lumos });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Welcome to Next.js</h1>
      </main>
    </>
  );
}
