import { RPC } from './types/rpc';
import { CKBComponents } from './types/api';
declare const formatter: {
    toOptional: (format?: Function | undefined) => (arg: any) => any;
    toArray: (format?: ((args: any) => any) | undefined) => (arg: any) => any;
    toHash: (hash: string) => RPC.Hash256;
    toNumber: (number: CKBComponents.Number | bigint) => RPC.Number;
    toScript: (script: CKBComponents.Script) => RPC.Script;
    toOutPoint: (outPoint: CKBComponents.OutPoint | undefined) => RPC.OutPoint | undefined;
    toInput: (input: CKBComponents.CellInput) => RPC.CellInput;
    toOutput: (output: CKBComponents.CellOutput) => RPC.CellOutput;
    toDepType: (type: CKBComponents.DepType) => "code" | "dep_group";
    toCellDep: (cellDep: CKBComponents.CellDep) => RPC.CellDep;
    toRawTransaction: (transaction: CKBComponents.RawTransaction) => RPC.RawTransaction;
    toPageNumber: (pageNo?: string | bigint) => string;
    toPageSize: (pageSize?: string | bigint) => string;
    toReverseOrder: (reverse?: boolean) => boolean;
    toOutputsValidator: (outputsValidator: CKBComponents.OutputsValidator) => import("../lib/types/api").CKBComponents.OutputsValidator;
    toBoolean: (value: boolean) => boolean;
    toTransactionProof: (proof: CKBComponents.TransactionProof) => RPC.TransactionProof;
};
export default formatter;
