version: '3.3'
services:
  ckb:
    image: lumos/ckb-dev:v0.103.0
    build: ckb
    ports:
      - '8128:8114'
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    internal: true
  external_network:

