name: Lint PR
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn add @commitlint/config-conventional -W
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0

